// lib/constants/tropes.dart
// Comprehensive deduplicated list of romance tropes

const List<String> romanceTropes = [
  'Accidental Adultery',
  'Accidental Pregnancy',
  'Age Gap',
  'Age Gap - Older Hero / Younger Heroine',
  'Age Gap - Younger Hero / Older Heroine',
  'Against the Odds',
  'All Grown Up',
  'Allergic to Commitment',
  'Aloof Couple',
  'Alpha Hero',
  'Already Married',
  'Always Right',
  'Amateur Detectives',
  'Amnesia',
  'Animal Wingman/Woman',
  'Anti-Hero',
  'Arranged Marriage',
  'Athlete',
  'Au-Pair',
  'Baby Makes Three',
  'Baby on the Doorstep',
  'Back from the Dead',
  'Bait and Switch',
  'Band of Brothers',
  'BDSM',
  'Beauty and the Beast',
  'Best Friend Triangle',
  'Best Friend\'s Partner',
  'Best Friend\'s Sibling',
  'Beta',
  'Betting',
  'Betty & Veronica Triangle',
  'Big City',
  'Billionaire Playboy',
  'Billionaires',
  'Bisexual Hero(ine)',
  'Blackmail',
  'Blind Date Mixup',
  'Blind Dates',
  'Blue Collar',
  'Bodyguard',
  'Bonding Through Pets',
  'Boyfriend/Girlfriend\'s Best Friend',
  'Break Up to Save Them',
  'Breeding',
  'Bridal Party',
  'Bridesmaid and Groomsman',
  'Bully Crush',
  'Bully Romance',
  'Captive Falls for Captor',
  'Care for the Injured',
  'Caretaker',
  'Celebrities',
  'Celibate Hero',
  'Childhood Friend',
  'Childhood Marriage Pact',
  'Childhood Sweethearts',
  'Christmas Romance',
  'Cinderella',
  'Cinderella Circumstance',
  'Coming of Age',
  'Coming Out',
  'Competition Rivals',
  'Cooking Show Romance',
  'Cougar',
  'Countryside',
  'Courtly Love',
  'Cowboy',
  'Cyrano',
  'Damsels Out of Distress',
  'Dangerous Attraction',
  'Dark Past',
  'Dating the Wrong Person',
  'Destiny',
  'Diamond in the Rough',
  'Different Worlds',
  'Diplomatic Marriage',
  'Disguise',
  'Doctor and Patient',
  'Dude in Distress',
  'Emotional Scars',
  'Enemies to Lovers',
  'Estranged Family',
  'Ethical Non-Monogamy',
  'Everyone Can See It Except Them',
  'Evil Stepmother',
  'Ex is Hanging Around',
  'Fairytale Retellings',
  'Fake Date',
  'Fake Death',
  'Fake Divorce',
  'Fake Engagement',
  'Fake Marriage',
  'Fake Relationship',
  'Falling in Love with Student\'s/Teacher\'s/Boss\' Parent',
  'Falling in Love with the Wrong Person',
  'Fated Mates',
  'Fear of Commitment',
  'FF',
  'Firefighter',
  'First Love',
  'Fish Out of Water',
  'Forbidden Love',
  'Forced Proximity',
  'Frenemies',
  'Friends to Lovers',
  'Friendship Circle',
  'Gay or Straight for You',
  'Girl Next Door',
  'Good Girls Want Bad Boys',
  'Grumpy vs. Sunshine',
  'Happy Ever After',
  'Happy for Now',
  'Harem',
  'Harem of Friends',
  'Hate to Love You',
  'High School Sweethearts',
  'Holidays',
  'Home for the Holidays',
  'Hookup',
  'Hunk',
  'I Can Fix Him',
  'In Love with Partner\'s Best Friend',
  'Infertility',
  'Innocent',
  'Innocent Cohabitation',
  'Instant Family',
  'Intergenerational Trauma',
  'Interfering Family',
  'Jilted',
  'Jilted Bride',
  'Jock and Cheerleader',
  'Jock and Nerd',
  'Jock Falls for Nerdy Tutor',
  'Just Friends',
  'Kidnapped',
  'Lady on the Streets, Freak in the Sheets',
  'Ladykiller in Love',
  'Landscaper',
  'Last to Know',
  'Lawyer',
  'Learn to Love',
  'Long Distance Relationships',
  'Love at First Sight',
  'Love Interest\'s Child Brings Everyone Together',
  'Love Interest\'s Child Tries to Break Couple Apart',
  'Love Letter Lunacy',
  'Love Potions',
  'Loveable Rogue',
  'Lovers in Denial',
  'Loving Thy Neighbor',
  'Magic',
  'Magical Romance',
  'Mafia',
  'Maid',
  'Mail-Order Bride',
  'Marriage of Convenience',
  'Marriage of Honour',
  'Marriage Pact',
  'Mary Sue',
  'Matchmaker',
  'Matchmaker Crush',
  'Matchmaker Gone Wrong',
  'May-December',
  'Medical',
  'Meet at the Wedding',
  'Meet Cute',
  'Men in Uniform',
  'MF',
  'MFF',
  'MFM',
  'Military Romance',
  'Miscommunication',
  'Mistaken Declaration of Love',
  'Mistaken Identity',
  'MM',
  'MMF',
  'Motorcycle',
  'Movie Star Falls for Commoner',
  'Nanny',
  'Neighbors',
  'New Old Flame',
  'Not Good Enough',
  'Not Good Enough for Them',
  'Not Like Other Girls',
  'Oblivious to Love',
  'Office Romance - Competition Rivals',
  'Office Romance - Coworkers w/ Benefits',
  'Older Couple',
  'On the Rocks',
  'One Bed',
  'One Night Stand',
  'Opposites - Bad Boy / Good Girl',
  'Opposites - Grumpy Sunshine',
  'Opposites - Playboy / Virgin',
  'Opposites Attract',
  'Orphan Bonding',
  'Orphans',
  'Outcast from Society',
  'Outsider',
  'Overprotective Brother',
  'Paramedic',
  'Paranormal',
  'Parents Finding New Love',
  'Pen Pals',
  'Penpal Enemy',
  'Person in Peril',
  'Physical Scars',
  'Physicality',
  'Pining After His Parent',
  'Playboy',
  'Playboy with Everyone But You',
  'Plus-Size',
  'Policeman',
  'Politician',
  'Polyamory',
  'Polyamory Love',
  'Polygamy',
  'Pool Boy',
  'Pop Star',
  'Possessive',
  'Power Dynamics',
  'Prank Date',
  'Pretty Boy',
  'Priest',
  'Prom Date',
  'Protective',
  'Puppy Hero',
  'Rake',
  'Reality TV',
  'Redemption Story',
  'Reformed Rakes',
  'Reformed Villain',
  'Rejected Past',
  'Relationship Coach',
  'Religious',
  'Rescuer',
  'Rescue Romance',
  'Resistant Children',
  'Reunion Romance',
  'Reverse Harem',
  'Reversal of Fortune',
  'Revenge Romance',
  'Riches to Rags',
  'Rich vs. Poor',
  'Right in Front of You All Along',
  'Rivals',
  'Road Trip',
  'Robot or Computer',
  'Rock Star',
  'Rockstar Romance',
  'Romance on Set',
  'Roommate Romance',
  'Roommates',
  'Royalty',
  'Royalty Falls for Commoner',
  'Runaway Bride',
  'Runaway Fiancé',
  'Saved from Attempted Rape or Assault',
  'Scars of the Past',
  'Scavenger Hunt Bonding',
  'Second Chance',
  'Secret Admirer',
  'Secret Billionaire',
  'Secret Boss',
  'Secret Heir',
  'Secret Identity',
  'Secret Lovechild',
  'Secret Past',
  'Secret Romance',
  'Secret Royal',
  'Secret Stalker',
  'Secrets',
  'Secretary',
  'Sex Club',
  'Sex Workers',
  'Shape Shifters',
  'Shared Past',
  'Sibling Triangle',
  'Sibling\'s Best Friend',
  'Sibling\'s Ex',
  'Silver Fox',
  'Single Parents',
  'Singles Pact',
  'Sleeping with the Boss',
  'Sleeping with the Teacher',
  'Small Town',
  'Soul Mates',
  'Sports Romance - Baseball',
  'Sports Romance - Basketball',
  'Sports Romance - Football / Rugby',
  'Sports Romance - Hockey',
  'Sports Romance - Lacrosse',
  'Sports Romance - Soccer',
  'Sports Romance - Tennis Instructor',
  'Sports Romance - Wrestling',
  'Sports Star',
  'Star-Crossed Lovers',
  'Step Siblings',
  'Step-Sibling Crush',
  'Stranded Together',
  'Summer Romance',
  'Surprise Baby',
  'Suspect and Detective',
  'Sworn Off Romance',
  'Tamed Rakes',
  'Teacher',
  'Teacher/Parent Relationship',
  'The Bet',
  'The Bodyguard',
  'The Doctor and Patient',
  'The Landscaper',
  'The Lawyer and Client',
  'The Maid',
  'The Nanny',
  'The No Feelings Hookup',
  'The One That Got Away',
  'The Pool Boy',
  'The Protector',
  'The Rich and the Poor',
  'The Ugly Duckling',
  'Therapist',
  'Time Travel',
  'Tortured Hero',
  'Tortured Lover',
  'Trapped',
  'Tropical Island',
  'Tug-of-War Triangle',
  'Twin Swap',
  'Two Person Love Triangle',
  'Unattainable Love Interest',
  'Undercover Detective',
  'Undercover Romance',
  'Unexpected Inheritance',
  'Unexpected Parent',
  'Unrequited Love',
  'Us Against the World',
  'Vampire and Werewolf Love Triangle',
  'Vampire-Werewolf Triangle',
  'Vegas Marriage',
  'Virgin',
  'Virgin Auction',
  'Wallflower',
  'Wanting Different Things',
  'Wartime Weddings',
  'Widow',
  'Work Romance',
  'Working with Their Ex',
  'Workplace Romance',
  'Wrong Side of the Tracks',
];

// Legacy export (deprecated, use romanceTropes instead)
@Deprecated('Use romanceTropes instead')
const List<String> commonTropes = romanceTropes;
