// lib/constants/tropes.dart

const List<String> commonTropes = [
  'Enemies to Lovers',
  'Grumpy Sunshine',
  'Mutual Pining',
  'Friends to Lovers',
  'Fake Dating',
  'Forbidden Love',
  'Second Chance',
  'Slow Burn',
  'Love Triangle',
  'Found Family',
  'Age Gap',
  'Secret Identity',
  'Marriage of Convenience',
  'Billionaire',
  'Small Town',
  'Workplace Romance',
  'Single Parent',
  'Amnesia',
  'Bodyguard',
  'Royalty',
  'Sports Romance',
  'Holiday Romance',
  'Roommates',
  'Best Friend’s Sibling',
  'Sibling’s Best Friend',
  'Arranged Marriage',
  'Redemption',
  'Opposites Attract',
  'Teacher/Student',
  'Celebrity',
  'Reunion',
  'Mistaken Identity',
  'Road Trip',
  'Revenge',
  'Wounded Hero',
  'Widow/Widower',
  'Disability',
  'Single Dad',
  'Single Mom',
  'Military',
  'Paranormal',
  'Historical',
  'Fantasy',
  'Sci-Fi',
  'Dark Romance',
  'Reverse Harem',
  'Polyamory',
  'LGBTQ+',
  'Coming of Age',
  'New Adult',
  'College',
  'Teacher',
  'Student',
  'Boss/Employee',
  'Neighbors',
  'Friends with Benefits',
  'One Night Stand',
  'Secret Baby',
  'Marriage in Trouble',
  'Divorce',
  'Adoption',
  'Stepbrother',
  'Stepsister',
  'Guardian/Ward',
  'May/December',
  'Taboo',
  'Monster Romance',
  'Omegaverse',
];
